### PR TITLE
bls fix + network change to dev

### LINKED ISSUE #121: Fix bls / network issue on bolt route
facing errors on bolt route refresh

### PR DESCRIPTION
**Pull request by usama-mk**
closes #121

### CODE REVIEW

File: src/screens/bolt/index.tsx [hunk 1]
```diff
@@ -71,9 +74,11 @@ export default function Bolt() {
     setIsLoading(false)
   }
   useEffect(() => {
+    if (!blsLoaded || isWasmInitializing) return
```
Comment (ranajahanzaib) [inline src/screens/bolt/index.tsx:77]: What do you think of if bls loaded and wasm is not initializing. call get balance, etc.?

**Review by ranajahanzaib — APPROVED** [review]
Excellent PR, @usama-mk 💪 🚀 💯

**Review by ranajahanzaib — APPROVED** [review]
